language: csharp
dist: xenial
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
dotnet: 3.1.401
mono: none
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_install:
  - apt-get install -y dotnet-sdk-2.1
  - chmod +x build.sh
script:
  - dotnet --info
  - ./build.sh -target=sonar
