apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice-stack.fullname" . }}-database
  labels:
    app: {{ template "microservice-stack.name" . }}-database
    chart: {{ template "microservice-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: database
      protocol: TCP
      name: database
  selector:
    app: {{ template "microservice-stack.name" . }}-database
    release: {{ .Release.Name }}
