apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice-stack.fullname" . }}-mailhog
  labels:
    app: {{ template "microservice-stack.name" . }}-mailhog
    chart: {{ template "microservice-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.mailhog.service.type }}
  ports:
    - port: {{ .Values.mailhog.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.mailhog.service.smtp.port }}
      protocol: TCP
      name: smtp
  selector:
    app: {{ template "microservice-stack.name" . }}-mailhog
    release: {{ .Release.Name }}
