apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "microservice-stack.fullname" . }}-mailhog
  labels:
    app: {{ template "microservice-stack.name" . }}-mailhog
    chart: {{ template "microservice-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mailhog.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "microservice-stack.name" . }}-mailhog
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "microservice-stack.name" . }}-mailhog
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.mailhog.name }}
          image: "{{ .Values.mailhog.image.repository }}"
          imagePullPolicy: {{ .Values.mailhog.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mailhog.service.http.port }}
              protocol: TCP
            - name: smtp
              containerPort: {{ .Values.mailhog.service.smtp.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
