apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice-stack.fullname" . }}-prometheus
  labels:
    app: {{ template "microservice-stack.name" . }}-prometheus
    chart: {{ template "microservice-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30990
  selector:
    app: {{ template "microservice-stack.name" . }}-prometheus
    release: {{ .Release.Name }}
