apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "coredatastore.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: {{ include "coredatastore.name" . }}-elasticsearch
    helm.sh/chart: {{ include "coredatastore.chart" . }}-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coredatastore.name" . }}-elasticsearch
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "coredatastore.name" . }}-elasticsearch
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.elasticsearch.image}}:{{ .Values.elasticsearch.tag }}
          ports:
            - containerPort: 9200
          env:
          - name: http.host
            value: {{ .Values.elasticsearch.httphost }}
          - name: transport.host
            value: {{ .Values.elasticsearch.transporthost }}
          - name: network.host
            value: {{ .Values.elasticsearch.networkhost }}
          - name: ES_JAVA_OPTS
            value: {{ .Values.elasticsearch.EsJavaOpts }}
          - name: ES_HEAP_SIZE
            value: {{ .Values.elasticsearch.EsHeapSize }}
