apiVersion: v1
kind: Service
metadata:
  name: graylog  
#  name: {{ include "coredatastore.fullname" . }}-graylog
  labels:
    app.kubernetes.io/name: {{ include "coredatastore.name" . }}-graylog
    helm.sh/chart: {{ include "coredatastore.chart" . }}-graylog
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.graylog.service.type }}
  ports:
    - name: port9000
      port: {{ .Values.graylog.service.ports.port9000 }}
    - name: port1514
      port: {{ .Values.graylog.service.ports.port1514 }}
    - name: port12201
      port: {{ .Values.graylog.service.ports.port12201 }}
  selector:
    app.kubernetes.io/name: {{ include "coredatastore.name" . }}-graylog
    app.kubernetes.io/instance: {{ .Release.Name }}
