apiVersion: v1
kind: ConfigMap
metadata:
  name: prom
  labels:
    app.kubernetes.io/name: prom
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
          monitor: 'prometheus-stack-monitor'

    # Load and evaluate rules in this file every 'evaluation_interval' seconds.
    rule_files:
      - 'alert.rules'
      - 'redis.rules'

    # alert
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"

    scrape_configs:

      - job_name: 'stub'
        file_sd_configs:
          - files:
            - /etc/prometheus/targets/*.json

      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
            - targets: ['localhost:9090']

      - job_name: 'redis-exporter'
        static_configs:
            - targets: ['redis-exporter:9121']

      - job_name: 'mongodb'
        static_configs:
            - targets: ['mongodb-exporter:9001']

      - job_name: 'cadvisor'
        scrape_interval: 5s
        static_configs:
            - targets: ['cadvisor:8080']

      - job_name: 'api-navigator-attractions'
        scrape_interval: 5s
        metrics_path: '/metrics-text'
        static_configs:
            - targets: ['api-navigator-attractions:7100']

      - job_name: 'api-navigator-reports'
        scrape_interval: 5s
        metrics_path: '/metrics-text'
        static_configs:
            - targets: ['api-navigator-reports:7200']

      - job_name: 'api-navigator-maps'
        scrape_interval: 5s
        metrics_path: '/metrics-text'
        static_configs:
            - targets: ['api-navigator-maps:7000']
