version: '3.3'

services:

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml
     # - ./example-data/tempo:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "31000:3100"   # tempo
    networks:
      - microservice-network

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.29
    volumes:
      - ./etc/load-generator.json:/etc/load-generator.json
      - ./tempo/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tempo:14268
    networks:
      - microservice-network

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" #ui dashboard
      - "4268:14268" #jaeger ingest
      - "4317:55680"  #oltp port
      - "14250:14250"
      - "9411:9411"
      - "13133:13133" #health check
    networks:
      - microservice-network