version: '3.3'

services:

  prometheus:
    image: stuartshay/microservice-prometheus:v2.26.0-v2.12
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - microservice-network

  grafana:
    image: stuartshay/microservice-grafana:7.5.4-v7.100
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/logs/:/var/log/grafana/grafana
      - ./grafana/config.ini:/etc/grafana/config.ini
    networks:
      - microservice-network  
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GRAFANA_HOST="http://grafana:3000"
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

volumes:
  prometheus_data:
  grafana_data:

networks:
 microservice-network:
