version: '2'

services:

  coredatastore_reporting_api:
    container_name: 'coredatastore-reporting-api'
    image: "stuartshay/coredatastore-reporting-api:2.0-build"
    depends_on:
     - database
    entrypoint: bash /wait_for_it.sh database:5432 -t 0 --  dotnet /publish/CoreDataStore.Reporting.WebAPI.dll
    ports:
     - "5900:5000"
    networks:
      - aspnetcoreapp-network

  database:
    container_name: 'database'
    image: "stuartshay/coredatastore-postgres"
    environment:
      POSTGRES_PASSWORD: password
    networks:
    - aspnetcoreapp-network


networks:
  aspnetcoreapp-network:
driver: bridge
