version: '3.3'

services:

  gdal:
    image: stuartshay/microservice-gdal:1.1.1-v1
    container_name: gdal
    volumes:
      - gdal_data:/gdal
    networks:
      - microservice-network
  
volumes:
  gdal_data:

networks:
 microservice-network:


