version: '2.0'

services:

  microservice-api:
    container_name: 'microservice-api'
    image: "stuartshay/microservice-api:2.2.1-build"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

  database:
    container_name: 'database'
    image: "stuartshay/microservice-database:v1"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:

