version: '2.0'

services:

  microservice-api:
    container_name: 'microservice-api'
    image: "stuartshay/microservice-api:2.2.1-build"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:

