global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  - 'redis.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"


scrape_configs:

  - job_name: 'stub'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
        - targets: ['localhost:9090']

  - job_name: 'microservice-api'
    scrape_interval: 5s
    metrics_path: '/metrics-text'
    static_configs:
        - targets: ['microservice-api:5000']

  - job_name: 'tempo'
    static_configs:
    - targets: ['tempo:3100']