name: Build/Test/Deploy
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: microservice-api
  REGION: us-east4
  ARTIFACT_REGISTRY_HOST: us-east4-docker.pkg.dev
  GCP_DOCKER_IMAGE: us-east4-docker.pkg.dev/velvety-byway-327718/microservice-api/microservice-api
  DH_DOCKER_IMAGE: stuartshay/microservice-api
  DOCKER_IMAGE_TAG: 5.1-buildx-${{ github.sha }}
  DOCKER_IMAGE_PLATFORM: linux/amd64,linux/arm/v7

on: 
  push:
   branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT }}
          export_default_credentials: true 

      - name: Use Google Cloud CLI
        run: gcloud info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Install dependencies
        run: dotnet restore

      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}

      - name: Build image
        id: docker_build
        run: |-
          docker buildx build . -f docker/microservice-api-multi.dockerfile/Dockerfile \
              --platform linux/amd64 \
              --output "type=image,push=false" \
              -t ${{ env.DH_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG}} \
              -t ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG}}

      - name: Google Cloud Artifacts/Authorize Docker push
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_HOST }}

      - name: GCP Artifact Registry
        run: docker push ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}-${{ steps.extract_branch.outputs.branch }}
          image:  ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}
          region: ${{ env.REGION }}
          flags: "--memory 1Gi --port 5000 --allow-unauthenticated"
