name: Gdal Tools

on:
  push:
    paths:
    - 'docker/gdal/**' 
    - '.github/workflows/gdal.workflow.yml'

    branches:
    - master
    - develop
    - 'feature/**'
    - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2









