name: Prometheus Workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-east4
  ARTIFACT_REGISTRY_HOST: us-east4-docker.pkg.dev
  GCP_DOCKER_IMAGE: us-east4-docker.pkg.dev/velvety-byway-327718/microservice-api/microservice-grafana
  DH_DOCKER_IMAGE: stuartshay/microservice-grafana
  DOCKER_IMAGE_TAG: 8.2.1-v7-${{ github.sha }}
  DOCKER_IMAGE_PLATFORM: linux/amd64,linux/arm/v7
  BUILD_NUMBER: ${{ github.sha }}

on:
  push:
    paths:
    - 'docker/prometheus/**' 
    - '.github/workflows/prometheus.workflow.yml'
     
    branches:
    - master
    - develop
    - 'feature/**'
    - 'fix/**'

jobs:
   Prometheus-Docker-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."