name: Prometheus Workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-east4
  ARTIFACT_REGISTRY_HOST: us-east4-docker.pkg.dev
  GCP_DOCKER_IMAGE: us-east4-docker.pkg.dev/velvety-byway-327718/microservice-api/microservice-prometheus
  DH_DOCKER_IMAGE: stuartshay/microservice-prometheus
  DOCKER_FILE: 'docker/prometheus/Dockerfile'
  DOCKER_IMAGE_TAG: v2.30.3-v2-${{ github.sha }}
  DOCKER_IMAGE_PLATFORM: linux/amd64,linux/arm/v7
  BUILD_NUMBER: ${{ github.sha }}

on:
  push:
    paths:
    - 'docker/prometheus/**' 
    - '.github/workflows/prometheus.workflow.yml'
     
    branches:
    - master
    - develop
    - 'feature/**'
    - 'fix/**'

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker_build
        run:  |
          echo "DOCKER FILE ${{ env.DOCKER_FILE }}"
          echo "GCP_DOCKER_IMAGE ${{ env.GCP_DOCKER_IMAGE}}:${{ env.DOCKER_IMAGE_TAG}}"

   publish:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2



