name: Shapefile Deployment

on:
  push:
    paths:
    - 'files/Borough_Boundaries/**' 
    - '.github/workflows/shapefile.yml'

    branches:
    - master
    - develop
    - 'feature/**'
    - 'fix/**'

jobs:
  copyfiles:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       service_account_key: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT }}
       project_id: ${{ secrets.gcp_project }}
       export_default_credentials: true


