name: Shapefile Deployment

on:
  push:
    paths:
    - 'files/Borough_Boundaries/**' 
    - '.github/workflows/shapefile.yml'

    branches:
    - master
    - develop
    - 'feature/**'
    - 'fix/**'

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
       project_id: ${{ secrets.gcp_project }}
       service_account_key: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT }}
       export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - id: upload-files
      uses: google-github-actions/upload-cloud-storage@main
      with:
       path: files/Borough_Boundaries
       destination: files-shapes

    - name: Upload raw artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Borough_Boundaries
          path: files/Borough_Boundaries

  transform:
    runs-on: ubuntu-latest
    needs: [ extract ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name:  Install ogr2ogr
        run: |
          echo "Install ogr2ogr"

      - name:  Shapefile to GeoJSON
        run: |
          echo "ogr2ogr files/Borough_Boundaries/nybb.shp =>  nybb.json "

      - name: Upload GeoJson artifacts
        run: |
          echo "Install ogr2ogr"

  load:
    runs-on: ubuntu-latest
    needs: [ copyfiles ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name:  Insert GeoJSON data
        run: |
          echo "Insert GeoJSON data"

      - name:  Validate GeoJSON Inserted
        run: |
          echo "Validate GeoJson Inserted"


          